name: testmod
version: 1.0.0
author: devinggo
license: MIT
description: Testmod 模块 - 由DevingGo代码生成器创建
homepage: ""
goVersion: 1.23+
tags: []
keywords: []
dependencies: {}
modules: []
files:
    go:
        - modules/testmod
        - modules/_/worker/testmod.go
        - modules/_/modules/testmod.go
        - modules/_/logic/testmod.go
    sql:
        - resource\migrations\20260304100717_testmod_module.up.sql
        - resource\migrations\20260304100717_testmod_module.down.sql
    static: []
    config: []
    other: []
    exclude: []
configMerge:
    enabled: false
    files: []
staticDeploy:
    enabled: false
    rules: []
hooks:
    preInstall: []
    postInstall: []
    preUninstall: []
    postUninstall: []
    preUpgrade: []
    postUpgrade: []
variables: {}
security:
    signature:
        enabled: false
        publicKey: ""
        algorithm: RSA
    permissions:
        fileSystem: true
        network: false
        database: true
        admin: false
    sensitiveFiles: []
