// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// codeGenFieldsDao is the data access object for table code_gen_fields.
type codeGenFieldsDao struct {
	*internal.CodeGenFieldsDao
}

var (
	// CodeGenFields is a globally accessible object for table code_gen_fields operations.
	CodeGenFields = codeGenFieldsDao{internal.NewCodeGenFieldsDao()}
)

// Add your custom methods and functionality below.
