// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// codeGenButtonsDao is the data access object for table code_gen_buttons.
type codeGenButtonsDao struct {
	*internal.CodeGenButtonsDao
}

var (
	// CodeGenButtons is a globally accessible object for table code_gen_buttons operations.
	CodeGenButtons = codeGenButtonsDao{internal.NewCodeGenButtonsDao()}
)

// Add your custom methods and functionality below.
